language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- export PATH=$PWD/phantomjs-2.0.0:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- npm test
- script/travis-deploy.sh
env:
  secure: IxCrZg+tqOsLbAh6Hu00CeID43n53xk9KvzXRqqqctH6N+NFn80sOtEc014D1i8rjtGWtzd6CNkad+lusNBtbPcikfSm1DzGgpg8YJl8PMuAVBq14Wfa0/OT2wG9uv59jq8IkhrE7hCSOmOPDu9lPQJw6yEuNP5RoJWVIZzpog8=
